// Code generated by MockGen. DO NOT EDIT.
// Source: internal/chain/adapter.go
//
// Generated by this command:
//
//	mockgen -source=internal/chain/adapter.go -destination=internal/chain/mocks/mock_adapter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	chain "github.com/kodax/koda-custody-indexer/internal/chain"
	gomock "go.uber.org/mock/gomock"
)

// MockChainAdapter is a mock of ChainAdapter interface.
type MockChainAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockChainAdapterMockRecorder
	isgomock struct{}
}

// MockChainAdapterMockRecorder is the mock recorder for MockChainAdapter.
type MockChainAdapterMockRecorder struct {
	mock *MockChainAdapter
}

// NewMockChainAdapter creates a new mock instance.
func NewMockChainAdapter(ctrl *gomock.Controller) *MockChainAdapter {
	mock := &MockChainAdapter{ctrl: ctrl}
	mock.recorder = &MockChainAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainAdapter) EXPECT() *MockChainAdapterMockRecorder {
	return m.recorder
}

// Chain mocks base method.
func (m *MockChainAdapter) Chain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Chain indicates an expected call of Chain.
func (mr *MockChainAdapterMockRecorder) Chain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chain", reflect.TypeOf((*MockChainAdapter)(nil).Chain))
}

// FetchNewSignatures mocks base method.
func (m *MockChainAdapter) FetchNewSignatures(ctx context.Context, address string, cursor *string, batchSize int) ([]chain.SignatureInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNewSignatures", ctx, address, cursor, batchSize)
	ret0, _ := ret[0].([]chain.SignatureInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNewSignatures indicates an expected call of FetchNewSignatures.
func (mr *MockChainAdapterMockRecorder) FetchNewSignatures(ctx, address, cursor, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNewSignatures", reflect.TypeOf((*MockChainAdapter)(nil).FetchNewSignatures), ctx, address, cursor, batchSize)
}

// FetchTransactions mocks base method.
func (m *MockChainAdapter) FetchTransactions(ctx context.Context, signatures []string) ([]json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTransactions", ctx, signatures)
	ret0, _ := ret[0].([]json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTransactions indicates an expected call of FetchTransactions.
func (mr *MockChainAdapterMockRecorder) FetchTransactions(ctx, signatures any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTransactions", reflect.TypeOf((*MockChainAdapter)(nil).FetchTransactions), ctx, signatures)
}

// GetHeadSequence mocks base method.
func (m *MockChainAdapter) GetHeadSequence(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeadSequence", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeadSequence indicates an expected call of GetHeadSequence.
func (mr *MockChainAdapterMockRecorder) GetHeadSequence(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeadSequence", reflect.TypeOf((*MockChainAdapter)(nil).GetHeadSequence), ctx)
}
