area/pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - internal/pipeline/**
          - internal/chain/**
          - cmd/indexer/**

area/sidecar:
  - changed-files:
      - any-glob-to-any-file:
          - sidecar/**
          - proto/**
          - pkg/generated/sidecar/**

area/storage:
  - changed-files:
      - any-glob-to-any-file:
          - internal/store/**
          - internal/domain/model/**

area/infra:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - deployments/**
          - Makefile
          - scripts/**

type/docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/**

