- name: type/task
  color: 0E8A16
  description: Planned implementation work
- name: type/bug
  color: D73A4A
  description: Incorrect behavior or regression
- name: type/docs
  color: 0075CA
  description: Documentation update
- name: type/chore
  color: C2E0C6
  description: Build, tooling, or maintenance
- name: area/pipeline
  color: BFD4F2
  description: Coordinator, fetcher, normalizer, ingester
- name: area/sidecar
  color: C5DEF5
  description: gRPC sidecar and plugin system
- name: area/storage
  color: F9D0C4
  description: PostgreSQL repositories and migrations
- name: area/infra
  color: D4C5F9
  description: CI, Docker, deployment, runtime operations
- name: priority/p0
  color: B60205
  description: Highest priority, immediate handling
- name: priority/p1
  color: D93F0B
  description: High priority
- name: priority/p2
  color: FBCA04
  description: Normal priority
- name: priority/p3
  color: 0E8A16
  description: Low priority
- name: sev0
  color: B60205
  description: Production outage or data corruption
- name: sev1
  color: D93F0B
  description: Critical user impact
- name: sev2
  color: FBCA04
  description: Moderate impact
- name: sev3
  color: 0E8A16
  description: Minor impact
- name: decision-needed
  color: 5319E7
  description: Owner decision is needed to proceed
- name: decision/major
  color: B60205
  description: Major decision requiring explicit owner input
- name: needs-opinion
  color: 8A2BE2
  description: Explicit owner opinion is required before continuing
- name: blocked
  color: 000000
  description: Work cannot proceed due to external dependency
- name: ready-for-review
  color: 1D76DB
  description: Implementation complete and ready for review
- name: autonomous
  color: 0052CC
  description: Eligible for autonomous agent execution
- name: ready
  color: 0E8A16
  description: Ready to be picked from autonomous queue
- name: in-progress
  color: FBCA04
  description: Currently being processed by agent loop
- name: risk/high
  color: B60205
  description: High-risk change requiring explicit human confirmation
- name: agent/needs-config
  color: CFD3D7
  description: Agent loop could not run because executor is not configured
- name: agent/discovered
  color: 1B4D3E
  description: Auto-generated by issue scout
- name: role/manager
  color: 0E4C92
  description: Work item owned by manager agent
- name: role/developer
  color: 1D76DB
  description: Work item owned by developer agent
- name: role/qa
  color: FBCA04
  description: Work item owned by QA agent
- name: role/planner
  color: 5319E7
  description: Work item owned by planning agent
- name: qa-ready
  color: C2E0C6
  description: Ready for QA agent validation
- name: qa-in-progress
  color: FEF2C0
  description: Currently being processed by QA agent
- name: qa/passed
  color: 0E8A16
  description: QA validation passed
- name: qa/failed
  color: D73A4A
  description: QA validation failed
- name: release/major
  color: B60205
  description: Next release should bump MAJOR
- name: release/minor
  color: FBCA04
  description: Next release should bump MINOR
- name: release/patch
  color: 0E8A16
  description: Next release should bump PATCH
