changelog:
  categories:
    - title: Breaking Changes
      labels:
        - release/major
        - decision/major
    - title: Features
      labels:
        - release/minor
        - type/task
    - title: Fixes
      labels:
        - release/patch
        - type/bug
    - title: Maintenance
      labels:
        - type/chore
        - type/docs
  exclude:
    labels:
      - skip-changelog
