// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/repository.go -destination=internal/store/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	model "github.com/emperorhan/multichain-indexer/internal/domain/model"
	store "github.com/emperorhan/multichain-indexer/internal/store"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTxBeginner is a mock of TxBeginner interface.
type MockTxBeginner struct {
	ctrl     *gomock.Controller
	recorder *MockTxBeginnerMockRecorder
	isgomock struct{}
}

// MockTxBeginnerMockRecorder is the mock recorder for MockTxBeginner.
type MockTxBeginnerMockRecorder struct {
	mock *MockTxBeginner
}

// NewMockTxBeginner creates a new mock instance.
func NewMockTxBeginner(ctrl *gomock.Controller) *MockTxBeginner {
	mock := &MockTxBeginner{ctrl: ctrl}
	mock.recorder = &MockTxBeginnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxBeginner) EXPECT() *MockTxBeginnerMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockTxBeginner) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockTxBeginnerMockRecorder) BeginTx(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockTxBeginner)(nil).BeginTx), ctx, opts)
}

// MockWatchedAddressRepository is a mock of WatchedAddressRepository interface.
type MockWatchedAddressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWatchedAddressRepositoryMockRecorder
	isgomock struct{}
}

// MockWatchedAddressRepositoryMockRecorder is the mock recorder for MockWatchedAddressRepository.
type MockWatchedAddressRepositoryMockRecorder struct {
	mock *MockWatchedAddressRepository
}

// NewMockWatchedAddressRepository creates a new mock instance.
func NewMockWatchedAddressRepository(ctrl *gomock.Controller) *MockWatchedAddressRepository {
	mock := &MockWatchedAddressRepository{ctrl: ctrl}
	mock.recorder = &MockWatchedAddressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchedAddressRepository) EXPECT() *MockWatchedAddressRepositoryMockRecorder {
	return m.recorder
}

// FindByAddress mocks base method.
func (m *MockWatchedAddressRepository) FindByAddress(ctx context.Context, chain model.Chain, network model.Network, address string) (*model.WatchedAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAddress", ctx, chain, network, address)
	ret0, _ := ret[0].(*model.WatchedAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAddress indicates an expected call of FindByAddress.
func (mr *MockWatchedAddressRepositoryMockRecorder) FindByAddress(ctx, chain, network, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAddress", reflect.TypeOf((*MockWatchedAddressRepository)(nil).FindByAddress), ctx, chain, network, address)
}

// GetActive mocks base method.
func (m *MockWatchedAddressRepository) GetActive(ctx context.Context, chain model.Chain, network model.Network) ([]model.WatchedAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, chain, network)
	ret0, _ := ret[0].([]model.WatchedAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockWatchedAddressRepositoryMockRecorder) GetActive(ctx, chain, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockWatchedAddressRepository)(nil).GetActive), ctx, chain, network)
}

// Upsert mocks base method.
func (m *MockWatchedAddressRepository) Upsert(ctx context.Context, addr *model.WatchedAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockWatchedAddressRepositoryMockRecorder) Upsert(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockWatchedAddressRepository)(nil).Upsert), ctx, addr)
}

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// BulkUpsertTx mocks base method.
func (m *MockTransactionRepository) BulkUpsertTx(ctx context.Context, tx *sql.Tx, txns []*model.Transaction) (map[string]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertTx", ctx, tx, txns)
	ret0, _ := ret[0].(map[string]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpsertTx indicates an expected call of BulkUpsertTx.
func (mr *MockTransactionRepositoryMockRecorder) BulkUpsertTx(ctx, tx, txns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertTx", reflect.TypeOf((*MockTransactionRepository)(nil).BulkUpsertTx), ctx, tx, txns)
}

// UpsertTx mocks base method.
func (m *MockTransactionRepository) UpsertTx(ctx context.Context, tx *sql.Tx, t *model.Transaction) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTx", ctx, tx, t)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTx indicates an expected call of UpsertTx.
func (mr *MockTransactionRepositoryMockRecorder) UpsertTx(ctx, tx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTx", reflect.TypeOf((*MockTransactionRepository)(nil).UpsertTx), ctx, tx, t)
}

// MockBalanceEventRepository is a mock of BalanceEventRepository interface.
type MockBalanceEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceEventRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceEventRepositoryMockRecorder is the mock recorder for MockBalanceEventRepository.
type MockBalanceEventRepositoryMockRecorder struct {
	mock *MockBalanceEventRepository
}

// NewMockBalanceEventRepository creates a new mock instance.
func NewMockBalanceEventRepository(ctrl *gomock.Controller) *MockBalanceEventRepository {
	mock := &MockBalanceEventRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceEventRepository) EXPECT() *MockBalanceEventRepositoryMockRecorder {
	return m.recorder
}

// BulkUpsertTx mocks base method.
func (m *MockBalanceEventRepository) BulkUpsertTx(ctx context.Context, tx *sql.Tx, events []*model.BalanceEvent) (store.BulkUpsertEventResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertTx", ctx, tx, events)
	ret0, _ := ret[0].(store.BulkUpsertEventResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpsertTx indicates an expected call of BulkUpsertTx.
func (mr *MockBalanceEventRepositoryMockRecorder) BulkUpsertTx(ctx, tx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertTx", reflect.TypeOf((*MockBalanceEventRepository)(nil).BulkUpsertTx), ctx, tx, events)
}

// UpsertTx mocks base method.
func (m *MockBalanceEventRepository) UpsertTx(ctx context.Context, tx *sql.Tx, be *model.BalanceEvent) (store.UpsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTx", ctx, tx, be)
	ret0, _ := ret[0].(store.UpsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTx indicates an expected call of UpsertTx.
func (mr *MockBalanceEventRepositoryMockRecorder) UpsertTx(ctx, tx, be any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTx", reflect.TypeOf((*MockBalanceEventRepository)(nil).UpsertTx), ctx, tx, be)
}

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// AdjustBalanceTx mocks base method.
func (m *MockBalanceRepository) AdjustBalanceTx(ctx context.Context, tx *sql.Tx, req store.AdjustRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustBalanceTx", ctx, tx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdjustBalanceTx indicates an expected call of AdjustBalanceTx.
func (mr *MockBalanceRepositoryMockRecorder) AdjustBalanceTx(ctx, tx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustBalanceTx", reflect.TypeOf((*MockBalanceRepository)(nil).AdjustBalanceTx), ctx, tx, req)
}

// BulkAdjustBalanceTx mocks base method.
func (m *MockBalanceRepository) BulkAdjustBalanceTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, items []store.BulkAdjustItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAdjustBalanceTx", ctx, tx, chain, network, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkAdjustBalanceTx indicates an expected call of BulkAdjustBalanceTx.
func (mr *MockBalanceRepositoryMockRecorder) BulkAdjustBalanceTx(ctx, tx, chain, network, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAdjustBalanceTx", reflect.TypeOf((*MockBalanceRepository)(nil).BulkAdjustBalanceTx), ctx, tx, chain, network, items)
}

// BulkGetAmountWithExistsTx mocks base method.
func (m *MockBalanceRepository) BulkGetAmountWithExistsTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, keys []store.BalanceKey) (map[store.BalanceKey]store.BalanceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkGetAmountWithExistsTx", ctx, tx, chain, network, keys)
	ret0, _ := ret[0].(map[store.BalanceKey]store.BalanceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkGetAmountWithExistsTx indicates an expected call of BulkGetAmountWithExistsTx.
func (mr *MockBalanceRepositoryMockRecorder) BulkGetAmountWithExistsTx(ctx, tx, chain, network, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkGetAmountWithExistsTx", reflect.TypeOf((*MockBalanceRepository)(nil).BulkGetAmountWithExistsTx), ctx, tx, chain, network, keys)
}

// GetByAddress mocks base method.
func (m *MockBalanceRepository) GetByAddress(ctx context.Context, chain model.Chain, network model.Network, address string) ([]model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAddress", ctx, chain, network, address)
	ret0, _ := ret[0].([]model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAddress indicates an expected call of GetByAddress.
func (mr *MockBalanceRepositoryMockRecorder) GetByAddress(ctx, chain, network, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAddress", reflect.TypeOf((*MockBalanceRepository)(nil).GetByAddress), ctx, chain, network, address)
}

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// BulkIsDeniedTx mocks base method.
func (m *MockTokenRepository) BulkIsDeniedTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, contractAddresses []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkIsDeniedTx", ctx, tx, chain, network, contractAddresses)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkIsDeniedTx indicates an expected call of BulkIsDeniedTx.
func (mr *MockTokenRepositoryMockRecorder) BulkIsDeniedTx(ctx, tx, chain, network, contractAddresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkIsDeniedTx", reflect.TypeOf((*MockTokenRepository)(nil).BulkIsDeniedTx), ctx, tx, chain, network, contractAddresses)
}

// BulkUpsertTx mocks base method.
func (m *MockTokenRepository) BulkUpsertTx(ctx context.Context, tx *sql.Tx, tokens []*model.Token) (map[string]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertTx", ctx, tx, tokens)
	ret0, _ := ret[0].(map[string]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpsertTx indicates an expected call of BulkUpsertTx.
func (mr *MockTokenRepositoryMockRecorder) BulkUpsertTx(ctx, tx, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertTx", reflect.TypeOf((*MockTokenRepository)(nil).BulkUpsertTx), ctx, tx, tokens)
}

// DenyTokenTx mocks base method.
func (m *MockTokenRepository) DenyTokenTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, contractAddress, reason, source string, score int16, signals []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenyTokenTx", ctx, tx, chain, network, contractAddress, reason, source, score, signals)
	ret0, _ := ret[0].(error)
	return ret0
}

// DenyTokenTx indicates an expected call of DenyTokenTx.
func (mr *MockTokenRepositoryMockRecorder) DenyTokenTx(ctx, tx, chain, network, contractAddress, reason, source, score, signals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenyTokenTx", reflect.TypeOf((*MockTokenRepository)(nil).DenyTokenTx), ctx, tx, chain, network, contractAddress, reason, source, score, signals)
}

// FindByID mocks base method.
func (m *MockTokenRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTokenRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTokenRepository)(nil).FindByID), ctx, id)
}

// UpsertTx mocks base method.
func (m *MockTokenRepository) UpsertTx(ctx context.Context, tx *sql.Tx, t *model.Token) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTx", ctx, tx, t)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTx indicates an expected call of UpsertTx.
func (mr *MockTokenRepositoryMockRecorder) UpsertTx(ctx, tx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTx", reflect.TypeOf((*MockTokenRepository)(nil).UpsertTx), ctx, tx, t)
}

// MockWatermarkRepository is a mock of WatermarkRepository interface.
type MockWatermarkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWatermarkRepositoryMockRecorder
	isgomock struct{}
}

// MockWatermarkRepositoryMockRecorder is the mock recorder for MockWatermarkRepository.
type MockWatermarkRepositoryMockRecorder struct {
	mock *MockWatermarkRepository
}

// NewMockWatermarkRepository creates a new mock instance.
func NewMockWatermarkRepository(ctrl *gomock.Controller) *MockWatermarkRepository {
	mock := &MockWatermarkRepository{ctrl: ctrl}
	mock.recorder = &MockWatermarkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatermarkRepository) EXPECT() *MockWatermarkRepositoryMockRecorder {
	return m.recorder
}

// GetWatermark mocks base method.
func (m *MockWatermarkRepository) GetWatermark(ctx context.Context, chain model.Chain, network model.Network) (*model.PipelineWatermark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatermark", ctx, chain, network)
	ret0, _ := ret[0].(*model.PipelineWatermark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatermark indicates an expected call of GetWatermark.
func (mr *MockWatermarkRepositoryMockRecorder) GetWatermark(ctx, chain, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatermark", reflect.TypeOf((*MockWatermarkRepository)(nil).GetWatermark), ctx, chain, network)
}

// RewindWatermarkTx mocks base method.
func (m *MockWatermarkRepository) RewindWatermarkTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, ingestedSequence int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RewindWatermarkTx", ctx, tx, chain, network, ingestedSequence)
	ret0, _ := ret[0].(error)
	return ret0
}

// RewindWatermarkTx indicates an expected call of RewindWatermarkTx.
func (mr *MockWatermarkRepositoryMockRecorder) RewindWatermarkTx(ctx, tx, chain, network, ingestedSequence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RewindWatermarkTx", reflect.TypeOf((*MockWatermarkRepository)(nil).RewindWatermarkTx), ctx, tx, chain, network, ingestedSequence)
}

// UpdateWatermarkTx mocks base method.
func (m *MockWatermarkRepository) UpdateWatermarkTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, ingestedSequence int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWatermarkTx", ctx, tx, chain, network, ingestedSequence)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWatermarkTx indicates an expected call of UpdateWatermarkTx.
func (mr *MockWatermarkRepositoryMockRecorder) UpdateWatermarkTx(ctx, tx, chain, network, ingestedSequence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWatermarkTx", reflect.TypeOf((*MockWatermarkRepository)(nil).UpdateWatermarkTx), ctx, tx, chain, network, ingestedSequence)
}

// MockIndexedBlockRepository is a mock of IndexedBlockRepository interface.
type MockIndexedBlockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIndexedBlockRepositoryMockRecorder
	isgomock struct{}
}

// MockIndexedBlockRepositoryMockRecorder is the mock recorder for MockIndexedBlockRepository.
type MockIndexedBlockRepositoryMockRecorder struct {
	mock *MockIndexedBlockRepository
}

// NewMockIndexedBlockRepository creates a new mock instance.
func NewMockIndexedBlockRepository(ctrl *gomock.Controller) *MockIndexedBlockRepository {
	mock := &MockIndexedBlockRepository{ctrl: ctrl}
	mock.recorder = &MockIndexedBlockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexedBlockRepository) EXPECT() *MockIndexedBlockRepositoryMockRecorder {
	return m.recorder
}

// BulkUpsertTx mocks base method.
func (m *MockIndexedBlockRepository) BulkUpsertTx(ctx context.Context, tx *sql.Tx, blocks []*model.IndexedBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertTx", ctx, tx, blocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpsertTx indicates an expected call of BulkUpsertTx.
func (mr *MockIndexedBlockRepositoryMockRecorder) BulkUpsertTx(ctx, tx, blocks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertTx", reflect.TypeOf((*MockIndexedBlockRepository)(nil).BulkUpsertTx), ctx, tx, blocks)
}

// DeleteFromBlockTx mocks base method.
func (m *MockIndexedBlockRepository) DeleteFromBlockTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, fromBlock int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromBlockTx", ctx, tx, chain, network, fromBlock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFromBlockTx indicates an expected call of DeleteFromBlockTx.
func (mr *MockIndexedBlockRepositoryMockRecorder) DeleteFromBlockTx(ctx, tx, chain, network, fromBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromBlockTx", reflect.TypeOf((*MockIndexedBlockRepository)(nil).DeleteFromBlockTx), ctx, tx, chain, network, fromBlock)
}

// GetByBlockNumber mocks base method.
func (m *MockIndexedBlockRepository) GetByBlockNumber(ctx context.Context, chain model.Chain, network model.Network, blockNumber int64) (*model.IndexedBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBlockNumber", ctx, chain, network, blockNumber)
	ret0, _ := ret[0].(*model.IndexedBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBlockNumber indicates an expected call of GetByBlockNumber.
func (mr *MockIndexedBlockRepositoryMockRecorder) GetByBlockNumber(ctx, chain, network, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBlockNumber", reflect.TypeOf((*MockIndexedBlockRepository)(nil).GetByBlockNumber), ctx, chain, network, blockNumber)
}

// GetUnfinalized mocks base method.
func (m *MockIndexedBlockRepository) GetUnfinalized(ctx context.Context, chain model.Chain, network model.Network) ([]model.IndexedBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnfinalized", ctx, chain, network)
	ret0, _ := ret[0].([]model.IndexedBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnfinalized indicates an expected call of GetUnfinalized.
func (mr *MockIndexedBlockRepositoryMockRecorder) GetUnfinalized(ctx, chain, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnfinalized", reflect.TypeOf((*MockIndexedBlockRepository)(nil).GetUnfinalized), ctx, chain, network)
}

// PurgeFinalizedBefore mocks base method.
func (m *MockIndexedBlockRepository) PurgeFinalizedBefore(ctx context.Context, chain model.Chain, network model.Network, beforeBlock int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeFinalizedBefore", ctx, chain, network, beforeBlock)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeFinalizedBefore indicates an expected call of PurgeFinalizedBefore.
func (mr *MockIndexedBlockRepositoryMockRecorder) PurgeFinalizedBefore(ctx, chain, network, beforeBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeFinalizedBefore", reflect.TypeOf((*MockIndexedBlockRepository)(nil).PurgeFinalizedBefore), ctx, chain, network, beforeBlock)
}

// UpdateFinalityTx mocks base method.
func (m *MockIndexedBlockRepository) UpdateFinalityTx(ctx context.Context, tx *sql.Tx, chain model.Chain, network model.Network, upToBlock int64, newState string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFinalityTx", ctx, tx, chain, network, upToBlock, newState)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFinalityTx indicates an expected call of UpdateFinalityTx.
func (mr *MockIndexedBlockRepositoryMockRecorder) UpdateFinalityTx(ctx, tx, chain, network, upToBlock, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFinalityTx", reflect.TypeOf((*MockIndexedBlockRepository)(nil).UpdateFinalityTx), ctx, tx, chain, network, upToBlock, newState)
}

// UpsertTx mocks base method.
func (m *MockIndexedBlockRepository) UpsertTx(ctx context.Context, tx *sql.Tx, block *model.IndexedBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTx", ctx, tx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTx indicates an expected call of UpsertTx.
func (mr *MockIndexedBlockRepositoryMockRecorder) UpsertTx(ctx, tx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTx", reflect.TypeOf((*MockIndexedBlockRepository)(nil).UpsertTx), ctx, tx, block)
}

// MockRuntimeConfigRepository is a mock of RuntimeConfigRepository interface.
type MockRuntimeConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockRuntimeConfigRepositoryMockRecorder is the mock recorder for MockRuntimeConfigRepository.
type MockRuntimeConfigRepositoryMockRecorder struct {
	mock *MockRuntimeConfigRepository
}

// NewMockRuntimeConfigRepository creates a new mock instance.
func NewMockRuntimeConfigRepository(ctrl *gomock.Controller) *MockRuntimeConfigRepository {
	mock := &MockRuntimeConfigRepository{ctrl: ctrl}
	mock.recorder = &MockRuntimeConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeConfigRepository) EXPECT() *MockRuntimeConfigRepositoryMockRecorder {
	return m.recorder
}

// GetActive mocks base method.
func (m *MockRuntimeConfigRepository) GetActive(ctx context.Context, chain model.Chain, network model.Network) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, chain, network)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockRuntimeConfigRepositoryMockRecorder) GetActive(ctx, chain, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockRuntimeConfigRepository)(nil).GetActive), ctx, chain, network)
}

// MockDashboardRepository is a mock of DashboardRepository interface.
type MockDashboardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardRepositoryMockRecorder
	isgomock struct{}
}

// MockDashboardRepositoryMockRecorder is the mock recorder for MockDashboardRepository.
type MockDashboardRepositoryMockRecorder struct {
	mock *MockDashboardRepository
}

// NewMockDashboardRepository creates a new mock instance.
func NewMockDashboardRepository(ctrl *gomock.Controller) *MockDashboardRepository {
	mock := &MockDashboardRepository{ctrl: ctrl}
	mock.recorder = &MockDashboardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardRepository) EXPECT() *MockDashboardRepositoryMockRecorder {
	return m.recorder
}

// CountWatchedAddresses mocks base method.
func (m *MockDashboardRepository) CountWatchedAddresses(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWatchedAddresses", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWatchedAddresses indicates an expected call of CountWatchedAddresses.
func (mr *MockDashboardRepositoryMockRecorder) CountWatchedAddresses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWatchedAddresses", reflect.TypeOf((*MockDashboardRepository)(nil).CountWatchedAddresses), ctx)
}

// GetAllWatermarks mocks base method.
func (m *MockDashboardRepository) GetAllWatermarks(ctx context.Context) ([]model.PipelineWatermark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWatermarks", ctx)
	ret0, _ := ret[0].([]model.PipelineWatermark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWatermarks indicates an expected call of GetAllWatermarks.
func (mr *MockDashboardRepositoryMockRecorder) GetAllWatermarks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWatermarks", reflect.TypeOf((*MockDashboardRepository)(nil).GetAllWatermarks), ctx)
}

// GetBalanceSummary mocks base method.
func (m *MockDashboardRepository) GetBalanceSummary(ctx context.Context, chain model.Chain, network model.Network) ([]store.DashboardAddressBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceSummary", ctx, chain, network)
	ret0, _ := ret[0].([]store.DashboardAddressBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceSummary indicates an expected call of GetBalanceSummary.
func (mr *MockDashboardRepositoryMockRecorder) GetBalanceSummary(ctx, chain, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceSummary", reflect.TypeOf((*MockDashboardRepository)(nil).GetBalanceSummary), ctx, chain, network)
}

// GetRecentEvents mocks base method.
func (m *MockDashboardRepository) GetRecentEvents(ctx context.Context, chain model.Chain, network model.Network, address string, limit, offset int) ([]store.DashboardEvent, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentEvents", ctx, chain, network, address, limit, offset)
	ret0, _ := ret[0].([]store.DashboardEvent)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRecentEvents indicates an expected call of GetRecentEvents.
func (mr *MockDashboardRepositoryMockRecorder) GetRecentEvents(ctx, chain, network, address, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentEvents", reflect.TypeOf((*MockDashboardRepository)(nil).GetRecentEvents), ctx, chain, network, address, limit, offset)
}
