// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emperorhan/multichain-indexer/pkg/generated/sidecar/v1 (interfaces: ChainDecoderClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/pipeline/normalizer/mocks/mock_decoder_client.go -package=mocks github.com/emperorhan/multichain-indexer/pkg/generated/sidecar/v1 ChainDecoderClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sidecarv1 "github.com/emperorhan/multichain-indexer/pkg/generated/sidecar/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockChainDecoderClient is a mock of ChainDecoderClient interface.
type MockChainDecoderClient struct {
	ctrl     *gomock.Controller
	recorder *MockChainDecoderClientMockRecorder
	isgomock struct{}
}

// MockChainDecoderClientMockRecorder is the mock recorder for MockChainDecoderClient.
type MockChainDecoderClientMockRecorder struct {
	mock *MockChainDecoderClient
}

// NewMockChainDecoderClient creates a new mock instance.
func NewMockChainDecoderClient(ctrl *gomock.Controller) *MockChainDecoderClient {
	mock := &MockChainDecoderClient{ctrl: ctrl}
	mock.recorder = &MockChainDecoderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainDecoderClient) EXPECT() *MockChainDecoderClientMockRecorder {
	return m.recorder
}

// DecodeSolanaTransactionBatch mocks base method.
func (m *MockChainDecoderClient) DecodeSolanaTransactionBatch(ctx context.Context, in *sidecarv1.DecodeSolanaTransactionBatchRequest, opts ...grpc.CallOption) (*sidecarv1.DecodeSolanaTransactionBatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DecodeSolanaTransactionBatch", varargs...)
	ret0, _ := ret[0].(*sidecarv1.DecodeSolanaTransactionBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeSolanaTransactionBatch indicates an expected call of DecodeSolanaTransactionBatch.
func (mr *MockChainDecoderClientMockRecorder) DecodeSolanaTransactionBatch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeSolanaTransactionBatch", reflect.TypeOf((*MockChainDecoderClient)(nil).DecodeSolanaTransactionBatch), varargs...)
}

// HealthCheck mocks base method.
func (m *MockChainDecoderClient) HealthCheck(ctx context.Context, in *sidecarv1.HealthCheckRequest, opts ...grpc.CallOption) (*sidecarv1.HealthCheckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HealthCheck", varargs...)
	ret0, _ := ret[0].(*sidecarv1.HealthCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockChainDecoderClientMockRecorder) HealthCheck(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockChainDecoderClient)(nil).HealthCheck), varargs...)
}
