#!/usr/bin/env bash
set -euo pipefail

# Manage local Ralph runtime profiles.
# Usage:
#   scripts/ralph_local_profile.sh list
#   scripts/ralph_local_profile.sh status
#   scripts/ralph_local_profile.sh set <절약|최적|퍼포먼스>

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

RALPH_ROOT="${RALPH_ROOT:-.ralph}"
PROFILE_FILE="${RALPH_ROOT}/profile.env"
PROFILE_STATE_FILE="${RALPH_ROOT}/state.profile"

usage() {
  cat <<'EOF'
Usage:
  ralph_local_profile.sh list
  ralph_local_profile.sh status
  ralph_local_profile.sh set <절약|최적|퍼포먼스>

Examples:
  ralph_local_profile.sh set 절약
  ralph_local_profile.sh set 최적
  ralph_local_profile.sh set 퍼포먼스
EOF
}

normalize_profile() {
  local raw="${1:-}"
  case "$(printf '%s' "${raw}" | tr '[:upper:]' '[:lower:]')" in
    절약|economy|eco|save|saver)
      echo "절약"
      ;;
    최적|optimal|balanced|balance)
      echo "최적"
      ;;
    퍼포먼스|performance|perf|max)
      echo "퍼포먼스"
      ;;
    *)
      return 1
      ;;
  esac
}

write_profile() {
  local profile="$1"
  local tmp_file
  tmp_file="$(mktemp)"

  case "${profile}" in
    절약)
      cat > "${tmp_file}" <<'EOF'
# Generated by scripts/ralph_local_profile.sh
RALPH_PROFILE_NAME=절약
PLANNING_CODEX_MODEL=gpt-5.3-codex-spark
AGENT_CODEX_MODEL_FAST=gpt-5.3-codex-spark
AGENT_CODEX_MODEL_COMPLEX=gpt-5.3-codex-spark
QA_TRIAGE_CODEX_MODEL=gpt-5.3-codex-spark
RALPH_SELF_HEAL_MODEL=gpt-5.3-codex-spark
RALPH_SELF_HEAL_MAX_ATTEMPTS=1
RALPH_VALIDATE_MODE=tiered
RALPH_VALIDATE_LIGHT_CMD='go test ./... -count=1'
RALPH_VALIDATE_FULL_EVERY=6
RALPH_PROMPT_CONTEXT_MAX_LINES=90
RALPH_PROMPT_CONTEXT_HEAD_LINES=45
RALPH_PROMPT_CONTEXT_TAIL_LINES=45
RALPH_PROMPT_CONTEXT_PLANNER_MAX_LINES=150
RALPH_PROMPT_CONTEXT_PLANNER_HEAD_LINES=75
RALPH_PROMPT_CONTEXT_PLANNER_TAIL_LINES=75
RALPH_PROMPT_CONTEXT_HIGH_RISK_MAX_LINES=120
RALPH_PROMPT_CONTEXT_HIGH_RISK_HEAD_LINES=60
RALPH_PROMPT_CONTEXT_HIGH_RISK_TAIL_LINES=60
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_MAX_LINES=90
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_HEAD_LINES=45
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_TAIL_LINES=45
EOF
      ;;
    최적)
      cat > "${tmp_file}" <<'EOF'
# Generated by scripts/ralph_local_profile.sh
RALPH_PROFILE_NAME=최적
PLANNING_CODEX_MODEL=gpt-5.3-codex
AGENT_CODEX_MODEL_FAST=gpt-5.3-codex-spark
AGENT_CODEX_MODEL_COMPLEX=gpt-5.3-codex
QA_TRIAGE_CODEX_MODEL=gpt-5.3-codex
RALPH_SELF_HEAL_MODEL=gpt-5.3-codex
RALPH_SELF_HEAL_MAX_ATTEMPTS=1
RALPH_VALIDATE_MODE=tiered
RALPH_VALIDATE_LIGHT_CMD='go test ./... -count=1'
RALPH_VALIDATE_FULL_EVERY=3
RALPH_PROMPT_CONTEXT_MAX_LINES=120
RALPH_PROMPT_CONTEXT_HEAD_LINES=60
RALPH_PROMPT_CONTEXT_TAIL_LINES=60
RALPH_PROMPT_CONTEXT_PLANNER_MAX_LINES=240
RALPH_PROMPT_CONTEXT_PLANNER_HEAD_LINES=120
RALPH_PROMPT_CONTEXT_PLANNER_TAIL_LINES=120
RALPH_PROMPT_CONTEXT_HIGH_RISK_MAX_LINES=180
RALPH_PROMPT_CONTEXT_HIGH_RISK_HEAD_LINES=90
RALPH_PROMPT_CONTEXT_HIGH_RISK_TAIL_LINES=90
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_MAX_LINES=120
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_HEAD_LINES=60
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_TAIL_LINES=60
EOF
      ;;
    퍼포먼스)
      cat > "${tmp_file}" <<'EOF'
# Generated by scripts/ralph_local_profile.sh
RALPH_PROFILE_NAME=퍼포먼스
PLANNING_CODEX_MODEL=gpt-5.3-codex
AGENT_CODEX_MODEL_FAST=gpt-5.3-codex
AGENT_CODEX_MODEL_COMPLEX=gpt-5.3-codex
QA_TRIAGE_CODEX_MODEL=gpt-5.3-codex
RALPH_SELF_HEAL_MODEL=gpt-5.3-codex
RALPH_SELF_HEAL_MAX_ATTEMPTS=3
RALPH_VALIDATE_MODE=tiered
RALPH_VALIDATE_LIGHT_CMD='go test ./... -count=1'
RALPH_VALIDATE_FULL_EVERY=1
RALPH_PROMPT_CONTEXT_MAX_LINES=220
RALPH_PROMPT_CONTEXT_HEAD_LINES=110
RALPH_PROMPT_CONTEXT_TAIL_LINES=110
RALPH_PROMPT_CONTEXT_PLANNER_MAX_LINES=280
RALPH_PROMPT_CONTEXT_PLANNER_HEAD_LINES=140
RALPH_PROMPT_CONTEXT_PLANNER_TAIL_LINES=140
RALPH_PROMPT_CONTEXT_HIGH_RISK_MAX_LINES=220
RALPH_PROMPT_CONTEXT_HIGH_RISK_HEAD_LINES=110
RALPH_PROMPT_CONTEXT_HIGH_RISK_TAIL_LINES=110
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_MAX_LINES=140
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_HEAD_LINES=70
RALPH_PROMPT_CONTEXT_PLANNING_FIRST_TAIL_LINES=70
EOF
      ;;
    *)
      rm -f "${tmp_file}"
      return 1
      ;;
  esac

  mkdir -p "${RALPH_ROOT}"
  mv "${tmp_file}" "${PROFILE_FILE}"
  printf '%s\n' "${profile}" > "${PROFILE_STATE_FILE}"
}

print_status() {
  local profile
  if [ -f "${PROFILE_STATE_FILE}" ]; then
    profile="$(awk 'NR==1{print;exit}' "${PROFILE_STATE_FILE}" 2>/dev/null || true)"
  fi
  if [ -z "${profile:-}" ] && [ -f "${PROFILE_FILE}" ]; then
    profile="$(awk -F= '/^RALPH_PROFILE_NAME=/{print $2;exit}' "${PROFILE_FILE}" 2>/dev/null || true)"
  fi
  [ -n "${profile:-}" ] || profile="최적(기본)"

  echo "profile=${profile}"
  echo "profile_file=${PROFILE_FILE}"
  if [ -f "${PROFILE_FILE}" ]; then
    awk -F= '
      /^PLANNING_CODEX_MODEL=|^AGENT_CODEX_MODEL_FAST=|^AGENT_CODEX_MODEL_COMPLEX=|^QA_TRIAGE_CODEX_MODEL=|^RALPH_SELF_HEAL_MODEL=|^RALPH_VALIDATE_FULL_EVERY=|^RALPH_PROMPT_CONTEXT_MAX_LINES=/ {
        print $1 "=" $2
      }
    ' "${PROFILE_FILE}"
  else
    echo "profile_file_missing=true"
  fi
}

CMD="${1:-status}"
case "${CMD}" in
  list)
    printf '%s\n' "절약" "최적" "퍼포먼스"
    ;;
  status)
    print_status
    ;;
  set)
    target="${2:-}"
    if [ -z "${target}" ]; then
      usage >&2
      exit 1
    fi
    normalized="$(normalize_profile "${target}")" || {
      echo "unknown profile: ${target}" >&2
      usage >&2
      exit 1
    }
    write_profile "${normalized}"
    echo "profile_set=${normalized}"
    echo "note=restart_required_for_running_loop"
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    normalized="$(normalize_profile "${CMD}" || true)"
    if [ -n "${normalized}" ]; then
      write_profile "${normalized}"
      echo "profile_set=${normalized}"
      echo "note=restart_required_for_running_loop"
      exit 0
    fi
    usage >&2
    exit 1
    ;;
esac
