#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   AGENT_EXEC_CMD='your executor command' \
#   PLANNING_EXEC_CMD='scripts/planning_executor.sh' \
#   AGENT_RUNNER='self-hosted' \
#   AGENT_RUNNER_PLANNER='self-hosted' \
#   AGENT_RUNNER_DEVELOPER='self-hosted' \
#   MANAGER_RUNNER='self-hosted' \
#   QA_RUNNER='self-hosted' \
#   SCOUT_RUNNER='self-hosted' \
#   RALPH_LOOP_ENABLED='true' \
#   AGENT_CODEX_MODEL='' \
#   AGENT_CODEX_MODEL_FAST='gpt-5.3-codex-spark' \
#   AGENT_CODEX_MODEL_COMPLEX='gpt-5.3-codex' \
#   AGENT_CODEX_SANDBOX='workspace-write' \
#   AGENT_CODEX_APPROVAL='never' \
#   AGENT_CODEX_SEARCH='true' \
#   AGENT_MAX_ISSUES_PER_RUN='2' \
#   AGENT_MAX_PLANNER_ISSUES_PER_RUN='1' \
#   AGENT_MAX_AUTO_RETRIES='2' \
#   DECISION_REMINDER_HOURS='24' \
#   AGENT_DEVELOPER_INCLUDE_LABELS='' \
#   AGENT_DEVELOPER_EXCLUDE_LABELS='role/planner,role/qa,decision/major' \
#   AGENT_SCOUT_ENABLED='true' \
#   SCOUT_MAX_ISSUES_PER_RUN='2' \
#   SCOUT_FAIL_WINDOW_HOURS='24' \
#   SCOUT_TODO_LIMIT='20' \
#   MANAGER_LOOP_ENABLED='true' \
#   MANAGER_MAX_SETS_PER_RUN='1' \
#   QA_ADDRESS_BATCH_SIZE='5' \
#   SOLANA_WHITELIST_FILE='configs/solana_whitelist_addresses.txt' \
#   SOLANA_WHITELIST_CSV='...' \
#   QA_LOOP_ENABLED='true' \
#   QA_MAX_ISSUES_PER_RUN='1' \
#   QA_EXEC_CMD='scripts/qa_executor.sh' \
#   QA_TRIAGE_ENABLED='true' \
#   QA_TRIAGE_EXEC_CMD='scripts/qa_triage_executor.sh' \
#   QA_TRIAGE_CODEX_MODEL='gpt-5.3-codex' \
#   QA_TRIAGE_CODEX_SANDBOX='workspace-write' \
#   QA_TRIAGE_CODEX_APPROVAL='never' \
#   QA_TRIAGE_CODEX_SEARCH='false' \
#   PLANNING_CODEX_MODEL='gpt-5.3-codex' \
#   PLANNING_CODEX_SANDBOX='workspace-write' \
#   PLANNING_CODEX_APPROVAL='never' \
#   PLANNING_CODEX_SEARCH='true' \
#   PLANNER_FANOUT_ENABLED='true' \
#   PLANNER_FANOUT_CMD='scripts/planner_fanout.sh' \
#   PLANNER_FANOUT_MAX_ISSUES='8' \
#   scripts/setup_agent_loop.sh [owner/repo]

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required. Install from https://cli.github.com/" >&2
  exit 1
fi

REPO="${1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
AGENT_EXEC_CMD_VALUE="${AGENT_EXEC_CMD:-}"
PLANNING_EXEC_CMD_VALUE="${PLANNING_EXEC_CMD:-scripts/planning_executor.sh}"
AGENT_RUNNER_VALUE="${AGENT_RUNNER:-}"
AGENT_RUNNER_PLANNER_VALUE="${AGENT_RUNNER_PLANNER:-}"
AGENT_RUNNER_DEVELOPER_VALUE="${AGENT_RUNNER_DEVELOPER:-}"
MANAGER_RUNNER_VALUE="${MANAGER_RUNNER:-}"
QA_RUNNER_VALUE="${QA_RUNNER:-}"
SCOUT_RUNNER_VALUE="${SCOUT_RUNNER:-}"
RALPH_LOOP_ENABLED_VALUE="${RALPH_LOOP_ENABLED:-true}"
AGENT_CODEX_MODEL_VALUE="${AGENT_CODEX_MODEL:-}"
AGENT_CODEX_MODEL_FAST_VALUE="${AGENT_CODEX_MODEL_FAST:-gpt-5.3-codex-spark}"
AGENT_CODEX_MODEL_COMPLEX_VALUE="${AGENT_CODEX_MODEL_COMPLEX:-gpt-5.3-codex}"
AGENT_CODEX_SANDBOX_VALUE="${AGENT_CODEX_SANDBOX:-workspace-write}"
AGENT_CODEX_APPROVAL_VALUE="${AGENT_CODEX_APPROVAL:-never}"
AGENT_CODEX_SEARCH_VALUE="${AGENT_CODEX_SEARCH:-true}"
AGENT_MAX_ISSUES_PER_RUN_VALUE="${AGENT_MAX_ISSUES_PER_RUN:-2}"
AGENT_MAX_PLANNER_ISSUES_PER_RUN_VALUE="${AGENT_MAX_PLANNER_ISSUES_PER_RUN:-1}"
AGENT_MAX_AUTO_RETRIES_VALUE="${AGENT_MAX_AUTO_RETRIES:-2}"
DECISION_REMINDER_HOURS_VALUE="${DECISION_REMINDER_HOURS:-24}"
AGENT_DEVELOPER_INCLUDE_LABELS_VALUE="${AGENT_DEVELOPER_INCLUDE_LABELS:-}"
AGENT_DEVELOPER_EXCLUDE_LABELS_VALUE="${AGENT_DEVELOPER_EXCLUDE_LABELS:-role/planner,role/qa,decision/major}"
AGENT_SCOUT_ENABLED_VALUE="${AGENT_SCOUT_ENABLED:-true}"
SCOUT_MAX_ISSUES_PER_RUN_VALUE="${SCOUT_MAX_ISSUES_PER_RUN:-2}"
SCOUT_FAIL_WINDOW_HOURS_VALUE="${SCOUT_FAIL_WINDOW_HOURS:-24}"
SCOUT_TODO_LIMIT_VALUE="${SCOUT_TODO_LIMIT:-20}"
MANAGER_LOOP_ENABLED_VALUE="${MANAGER_LOOP_ENABLED:-true}"
MANAGER_MAX_SETS_PER_RUN_VALUE="${MANAGER_MAX_SETS_PER_RUN:-1}"
QA_ADDRESS_BATCH_SIZE_VALUE="${QA_ADDRESS_BATCH_SIZE:-5}"
SOLANA_WHITELIST_FILE_VALUE="${SOLANA_WHITELIST_FILE:-configs/solana_whitelist_addresses.txt}"
SOLANA_WHITELIST_CSV_VALUE="${SOLANA_WHITELIST_CSV:-}"
QA_LOOP_ENABLED_VALUE="${QA_LOOP_ENABLED:-true}"
QA_MAX_ISSUES_PER_RUN_VALUE="${QA_MAX_ISSUES_PER_RUN:-1}"
QA_EXEC_CMD_VALUE="${QA_EXEC_CMD:-scripts/qa_executor.sh}"
QA_TRIAGE_ENABLED_VALUE="${QA_TRIAGE_ENABLED:-true}"
QA_TRIAGE_EXEC_CMD_VALUE="${QA_TRIAGE_EXEC_CMD:-scripts/qa_triage_executor.sh}"
QA_TRIAGE_CODEX_MODEL_VALUE="${QA_TRIAGE_CODEX_MODEL:-gpt-5.3-codex}"
QA_TRIAGE_CODEX_SANDBOX_VALUE="${QA_TRIAGE_CODEX_SANDBOX:-workspace-write}"
QA_TRIAGE_CODEX_APPROVAL_VALUE="${QA_TRIAGE_CODEX_APPROVAL:-never}"
QA_TRIAGE_CODEX_SEARCH_VALUE="${QA_TRIAGE_CODEX_SEARCH:-false}"
PLANNING_CODEX_MODEL_VALUE="${PLANNING_CODEX_MODEL:-gpt-5.3-codex}"
PLANNING_CODEX_SANDBOX_VALUE="${PLANNING_CODEX_SANDBOX:-workspace-write}"
PLANNING_CODEX_APPROVAL_VALUE="${PLANNING_CODEX_APPROVAL:-never}"
PLANNING_CODEX_SEARCH_VALUE="${PLANNING_CODEX_SEARCH:-true}"
PLANNER_FANOUT_ENABLED_VALUE="${PLANNER_FANOUT_ENABLED:-true}"
PLANNER_FANOUT_CMD_VALUE="${PLANNER_FANOUT_CMD:-scripts/planner_fanout.sh}"
PLANNER_FANOUT_MAX_ISSUES_VALUE="${PLANNER_FANOUT_MAX_ISSUES:-8}"

if [ -z "${AGENT_EXEC_CMD_VALUE}" ]; then
  echo "AGENT_EXEC_CMD is required." >&2
  echo "Example: AGENT_EXEC_CMD='make test && make lint' scripts/setup_agent_loop.sh ${REPO}" >&2
  exit 1
fi

set_repo_var() {
  local name="$1"
  local value="$2"
  gh variable set "${name}" --repo "${REPO}" --body "${value}" >/dev/null
  echo "set ${name}"
}

echo "Configuring agent loop variables on ${REPO}"
set_repo_var "AGENT_EXEC_CMD" "${AGENT_EXEC_CMD_VALUE}"
set_repo_var "PLANNING_EXEC_CMD" "${PLANNING_EXEC_CMD_VALUE}"
set_repo_var "RALPH_LOOP_ENABLED" "${RALPH_LOOP_ENABLED_VALUE}"
if [ -n "${AGENT_CODEX_MODEL_VALUE}" ]; then
  set_repo_var "AGENT_CODEX_MODEL" "${AGENT_CODEX_MODEL_VALUE}"
else
  gh variable delete "AGENT_CODEX_MODEL" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset AGENT_CODEX_MODEL"
fi
set_repo_var "AGENT_CODEX_MODEL_FAST" "${AGENT_CODEX_MODEL_FAST_VALUE}"
set_repo_var "AGENT_CODEX_MODEL_COMPLEX" "${AGENT_CODEX_MODEL_COMPLEX_VALUE}"
set_repo_var "AGENT_CODEX_SANDBOX" "${AGENT_CODEX_SANDBOX_VALUE}"
set_repo_var "AGENT_CODEX_APPROVAL" "${AGENT_CODEX_APPROVAL_VALUE}"
set_repo_var "AGENT_CODEX_SEARCH" "${AGENT_CODEX_SEARCH_VALUE}"
set_repo_var "AGENT_MAX_ISSUES_PER_RUN" "${AGENT_MAX_ISSUES_PER_RUN_VALUE}"
set_repo_var "AGENT_MAX_PLANNER_ISSUES_PER_RUN" "${AGENT_MAX_PLANNER_ISSUES_PER_RUN_VALUE}"
set_repo_var "AGENT_MAX_AUTO_RETRIES" "${AGENT_MAX_AUTO_RETRIES_VALUE}"
set_repo_var "DECISION_REMINDER_HOURS" "${DECISION_REMINDER_HOURS_VALUE}"
if [ -n "${AGENT_DEVELOPER_INCLUDE_LABELS_VALUE}" ]; then
  set_repo_var "AGENT_DEVELOPER_INCLUDE_LABELS" "${AGENT_DEVELOPER_INCLUDE_LABELS_VALUE}"
else
  gh variable delete "AGENT_DEVELOPER_INCLUDE_LABELS" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset AGENT_DEVELOPER_INCLUDE_LABELS"
fi
set_repo_var "AGENT_DEVELOPER_EXCLUDE_LABELS" "${AGENT_DEVELOPER_EXCLUDE_LABELS_VALUE}"
set_repo_var "AGENT_SCOUT_ENABLED" "${AGENT_SCOUT_ENABLED_VALUE}"
set_repo_var "SCOUT_MAX_ISSUES_PER_RUN" "${SCOUT_MAX_ISSUES_PER_RUN_VALUE}"
set_repo_var "SCOUT_FAIL_WINDOW_HOURS" "${SCOUT_FAIL_WINDOW_HOURS_VALUE}"
set_repo_var "SCOUT_TODO_LIMIT" "${SCOUT_TODO_LIMIT_VALUE}"
set_repo_var "MANAGER_LOOP_ENABLED" "${MANAGER_LOOP_ENABLED_VALUE}"
set_repo_var "MANAGER_MAX_SETS_PER_RUN" "${MANAGER_MAX_SETS_PER_RUN_VALUE}"
set_repo_var "QA_ADDRESS_BATCH_SIZE" "${QA_ADDRESS_BATCH_SIZE_VALUE}"
set_repo_var "SOLANA_WHITELIST_FILE" "${SOLANA_WHITELIST_FILE_VALUE}"
set_repo_var "QA_LOOP_ENABLED" "${QA_LOOP_ENABLED_VALUE}"
set_repo_var "QA_MAX_ISSUES_PER_RUN" "${QA_MAX_ISSUES_PER_RUN_VALUE}"
set_repo_var "QA_EXEC_CMD" "${QA_EXEC_CMD_VALUE}"
set_repo_var "QA_TRIAGE_ENABLED" "${QA_TRIAGE_ENABLED_VALUE}"
set_repo_var "QA_TRIAGE_EXEC_CMD" "${QA_TRIAGE_EXEC_CMD_VALUE}"
set_repo_var "QA_TRIAGE_CODEX_MODEL" "${QA_TRIAGE_CODEX_MODEL_VALUE}"
set_repo_var "QA_TRIAGE_CODEX_SANDBOX" "${QA_TRIAGE_CODEX_SANDBOX_VALUE}"
set_repo_var "QA_TRIAGE_CODEX_APPROVAL" "${QA_TRIAGE_CODEX_APPROVAL_VALUE}"
set_repo_var "QA_TRIAGE_CODEX_SEARCH" "${QA_TRIAGE_CODEX_SEARCH_VALUE}"
set_repo_var "PLANNING_CODEX_MODEL" "${PLANNING_CODEX_MODEL_VALUE}"
set_repo_var "PLANNING_CODEX_SANDBOX" "${PLANNING_CODEX_SANDBOX_VALUE}"
set_repo_var "PLANNING_CODEX_APPROVAL" "${PLANNING_CODEX_APPROVAL_VALUE}"
set_repo_var "PLANNING_CODEX_SEARCH" "${PLANNING_CODEX_SEARCH_VALUE}"
set_repo_var "PLANNER_FANOUT_ENABLED" "${PLANNER_FANOUT_ENABLED_VALUE}"
set_repo_var "PLANNER_FANOUT_CMD" "${PLANNER_FANOUT_CMD_VALUE}"
set_repo_var "PLANNER_FANOUT_MAX_ISSUES" "${PLANNER_FANOUT_MAX_ISSUES_VALUE}"

if [ -n "${SOLANA_WHITELIST_CSV_VALUE}" ]; then
  set_repo_var "SOLANA_WHITELIST_CSV" "${SOLANA_WHITELIST_CSV_VALUE}"
fi

if [ -n "${AGENT_RUNNER_VALUE}" ]; then
  set_repo_var "AGENT_RUNNER" "${AGENT_RUNNER_VALUE}"
fi

if [ -n "${AGENT_RUNNER_PLANNER_VALUE}" ]; then
  set_repo_var "AGENT_RUNNER_PLANNER" "${AGENT_RUNNER_PLANNER_VALUE}"
else
  gh variable delete "AGENT_RUNNER_PLANNER" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset AGENT_RUNNER_PLANNER"
fi

if [ -n "${AGENT_RUNNER_DEVELOPER_VALUE}" ]; then
  set_repo_var "AGENT_RUNNER_DEVELOPER" "${AGENT_RUNNER_DEVELOPER_VALUE}"
else
  gh variable delete "AGENT_RUNNER_DEVELOPER" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset AGENT_RUNNER_DEVELOPER"
fi

if [ -n "${MANAGER_RUNNER_VALUE}" ]; then
  set_repo_var "MANAGER_RUNNER" "${MANAGER_RUNNER_VALUE}"
else
  gh variable delete "MANAGER_RUNNER" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset MANAGER_RUNNER"
fi

if [ -n "${QA_RUNNER_VALUE}" ]; then
  set_repo_var "QA_RUNNER" "${QA_RUNNER_VALUE}"
else
  gh variable delete "QA_RUNNER" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset QA_RUNNER"
fi

if [ -n "${SCOUT_RUNNER_VALUE}" ]; then
  set_repo_var "SCOUT_RUNNER" "${SCOUT_RUNNER_VALUE}"
else
  gh variable delete "SCOUT_RUNNER" --repo "${REPO}" >/dev/null 2>&1 || true
  echo "unset SCOUT_RUNNER"
fi

echo "Done."
echo "Next:"
echo "1) Ensure .github/workflows/agent-loop.yml is enabled"
echo "2) Create Autonomous Task issues with labels: autonomous + ready"
echo "3) Protect main branch (scripts/setup_branch_protection.sh ${REPO} main)"
