// Code generated by MockGen. DO NOT EDIT.
// Source: internal/chain/solana/rpc/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/chain/solana/rpc/client.go -destination=internal/chain/solana/rpc/mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	rpc "github.com/emperorhan/multichain-indexer/internal/chain/solana/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockRPCClient is a mock of RPCClient interface.
type MockRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockRPCClientMockRecorder
	isgomock struct{}
}

// MockRPCClientMockRecorder is the mock recorder for MockRPCClient.
type MockRPCClientMockRecorder struct {
	mock *MockRPCClient
}

// NewMockRPCClient creates a new mock instance.
func NewMockRPCClient(ctrl *gomock.Controller) *MockRPCClient {
	mock := &MockRPCClient{ctrl: ctrl}
	mock.recorder = &MockRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCClient) EXPECT() *MockRPCClientMockRecorder {
	return m.recorder
}

// GetSignaturesForAddress mocks base method.
func (m *MockRPCClient) GetSignaturesForAddress(ctx context.Context, address string, opts *rpc.GetSignaturesOpts) ([]rpc.SignatureInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignaturesForAddress", ctx, address, opts)
	ret0, _ := ret[0].([]rpc.SignatureInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignaturesForAddress indicates an expected call of GetSignaturesForAddress.
func (mr *MockRPCClientMockRecorder) GetSignaturesForAddress(ctx, address, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignaturesForAddress", reflect.TypeOf((*MockRPCClient)(nil).GetSignaturesForAddress), ctx, address, opts)
}

// GetSlot mocks base method.
func (m *MockRPCClient) GetSlot(ctx context.Context, commitment string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlot", ctx, commitment)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlot indicates an expected call of GetSlot.
func (mr *MockRPCClientMockRecorder) GetSlot(ctx, commitment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlot", reflect.TypeOf((*MockRPCClient)(nil).GetSlot), ctx, commitment)
}

// GetTransaction mocks base method.
func (m *MockRPCClient) GetTransaction(ctx context.Context, signature string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, signature)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockRPCClientMockRecorder) GetTransaction(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockRPCClient)(nil).GetTransaction), ctx, signature)
}
